# Shared privacy defaults for interactive shells and child processes.
export DO_NOT_TRACK=1
export RTK_TELEMETRY_DISABLED=1
export CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC=1
export DISABLE_TELEMETRY=1
export DISABLE_ERROR_REPORTING=1
export DISABLE_BUG_COMMAND=1
export OTEL_SDK_DISABLED=true
export CHECKPOINT_DISABLE=1
export DOTNET_CLI_TELEMETRY_OPTOUT=1
export POWERSHELL_TELEMETRY_OPTOUT=1
